// <auto-generated />
using System;
using AshtavinayakAPP.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AshtavinayakAPP.Migrations
{
    [DbContext(typeof(AshtvinayakTravelContext))]
    [Migration("20260724092847_AddAgentsAndCommission")]
    partial class AddAgentsAndCommission
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AshtavinayakAPP.Models.Agent", b =>
                {
                    b.Property<int>("AgentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AgentId"));

                    b.Property<string>("AadhaarDocumentPath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ApprovalStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Pending");

                    b.Property<string>("BusinessName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal?>("CommissionPercentage")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("RejectionRemarks")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ShopActLicenseDocumentPath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("UdyamCertificatePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("AgentId");

                    b.HasIndex(new[] { "Email" }, "UQ_Agents_Email")
                        .IsUnique();

                    b.HasIndex(new[] { "MobileNumber" }, "UQ_Agents_MobileNumber")
                        .IsUnique();

                    b.ToTable("Agents");
                });

            modelBuilder.Entity("AshtavinayakAPP.Models.Booking", b =>
                {
                    b.Property<int>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("BookingID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingId"));

                    b.Property<decimal?>("Advance")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int?>("AgentId")
                        .HasColumnType("int");

                    b.Property<string>("BookingCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("BookingDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("BookingSeatId")
                        .HasColumnType("int")
                        .HasColumnName("BookingSeatID");

                    b.Property<decimal?>("CommissionAmount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("CommissionPercentage")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<string>("Droppoint")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("DroppointId")
                        .HasColumnType("int")
                        .HasColumnName("DroppointID");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("PickUpPointName")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("PickupPointId")
                        .HasColumnType("int")
                        .HasColumnName("PickupPointID");

                    b.Property<string>("RoomType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Pending");

                    b.Property<decimal?>("TotalPayment")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int?>("TripId")
                        .HasColumnType("int")
                        .HasColumnName("TripID");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("BookingId")
                        .HasName("PK_Bookings_73951ACD69F68546");

                    b.HasIndex("AgentId");

                    b.HasIndex("PickupPointId");

                    b.HasIndex("TripId");

                    b.HasIndex("UserId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("AshtavinayakAPP.Models.BookingSeat", b =>
                {
                    b.Property<int>("BookingSeatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("BookingSeatID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingSeatId"));

                    b.Property<int?>("Adults")
                        .HasColumnType("int");

                    b.Property<int?>("BookingId")
                        .HasColumnType("int")
                        .HasColumnName("BookingID");

                    b.Property<int?>("Childwithoutseat")
                        .HasColumnType("int");

                    b.Property<int?>("Childwithseat")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("SeatNumber")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("TripId")
                        .HasColumnType("int")
                        .HasColumnName("TripID");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("BookingSeatId")
                        .HasName("PK_BookingS_FA4B94265F1E2627");

                    b.HasIndex("UserId");

                    b.HasIndex("TripId", "SeatNumber")
                        .IsUnique()
                        .HasDatabaseName("UQ_BookingSeats_TripId_SeatNumber_Active")
                        .HasFilter("[IsDeleted] = 0 AND [TripID] IS NOT NULL AND [SeatNumber] IS NOT NULL");

                    b.ToTable("BookingSeats");
                });

            modelBuilder.Entity("AshtavinayakAPP.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CategoryID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int?>("CityId")
                        .HasColumnType("int")
                        .HasColumnName("CityID");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("TourDestinationId")
                        .HasColumnType("int");

                    b.HasKey("CategoryId")
                        .HasName("PK_Categori_19093A2BEDFA3BB5");

                    b.HasIndex("CityId");

                    b.HasIndex("TourDestinationId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("AshtavinayakAPP.Models.City", b =>
                {
                    b.Property<int>("CityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CityID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CityId"));

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.HasKey("CityId")
                        .HasName("PK__Cities__F2D21A962DFD6CCF");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("AshtavinayakAPP.Models.CommissionSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("DefaultCommissionPercentage")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("Id");

                    b.ToTable("CommissionSettings");
                });

            modelBuilder.Entity("AshtavinayakAPP.Models.DropUp", b =>
                {
                    b.Property<int>("DroppointId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("DroppointId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DroppointId"));

                    b.Property<int?>("CityId")
                        .HasColumnType("int")
                        .HasColumnName("CityID");

                    b.Property<string>("DropPoint")
                        .HasMaxLength(700)
                        .HasColumnType("nvarchar(700)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.HasKey("DroppointId");

                    b.HasIndex("CityId");

                    b.ToTable("DropUp", (string)null);
                });

            modelBuilder.Entity("AshtavinayakAPP.Models.FamilyBooking", b =>
                {
                    b.Property<int>("FamilyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("FamilyID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FamilyId"));

                    b.Property<int?>("Adults")
                        .HasColumnType("int")
                        .HasColumnName("Adults");

                    b.Property<DateTime?>("BookingDate")
                        .HasColumnType("datetime")
                        .HasColumnName("BookingDate");

                    b.Property<int>("BookingId")
                        .HasColumnType("int")
                        .HasColumnName("BookingID");

                    b.Property<string>("CarType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("Childwithoutseat")
                        .HasColumnType("int")
                        .HasColumnName("Childwithoutseat");

                    b.Property<int?>("Childwithseat")
                        .HasColumnType("int")
                        .HasColumnName("Childwithseat");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("PackageId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("FamilyId");

                    b.HasIndex("PackageId");

                    b.HasIndex("UserId");

                    b.ToTable("FamilyBooking", (string)null);
                });

            modelBuilder.Entity("AshtavinayakAPP.Models.History", b =>
                {
                    b.Property<int>("HistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("HistoryID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HistoryId"));

                    b.Property<int?>("BookingId")
                        .HasColumnType("int")
                        .HasColumnName("BookingID");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int")
                        .HasColumnName("CategoryID");

                    b.Property<int?>("CityId")
                        .HasColumnType("int")
                        .HasColumnName("CityID");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("PackageId")
                        .HasColumnType("int")
                        .HasColumnName("PackageID");

                    b.HasKey("HistoryId");

                    b.HasIndex("BookingId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CityId");

                    b.HasIndex("PackageId");

                    b.ToTable("History", (string)null);
                });

            modelBuilder.Entity("AshtavinayakAPP.Models.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("NotificationDate")
                        .HasColumnType("datetime");

                    b.Property<string>("NotificationMessage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TripId")
                        .HasColumnType("int")
                        .HasColumnName("TripID");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.Property<int?>("VehicleId")
                        .HasColumnType("int");

                    b.HasKey("NotificationId")
                        .HasName("PK_Notifica_20CF2E124C36D041");

                    b.HasIndex("TripId");

                    b.HasIndex("UserId");

                    b.HasIndex("VehicleId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("AshtavinayakAPP.Models.Package", b =>
                {
                    b.Property<int>("PackageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PackageID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PackageId"));

                    b.Property<int?>("AdultPrice")
                        .HasColumnType("int");

                    b.Property<int?>("CarPackagePrice")
                        .HasColumnType("int");

                    b.Property<int?>("CarTotalSeat")
                        .HasColumnType("int");

                    b.Property<string>("CarType")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int")
                        .HasColumnName("CategoryID");

                    b.Property<int?>("Child3To8YrsWithoutSeat")
                        .HasColumnType("int");

                    b.Property<int?>("Child3To8YrswithSeat")
                        .HasColumnType("int");

                    b.Property<int?>("CityId")
                        .HasColumnType("int")
                        .HasColumnName("CityID");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Exclusions")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("Inclusions")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<bool>("IsCar")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Itinerary")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("PackageName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("PkgPersonCount")
                        .HasColumnType("int");

                    b.HasKey("PackageId")
                        .HasName("PK_Packages_322035ECADB4B945");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CityId");

                    b.ToTable("Packages");
                });

            modelBuilder.Entity("AshtavinayakAPP.Models.PickupPoint", b =>
                {
                    b.Property<int>("PickupPointId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PickupPointID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PickupPointId"));

                    b.Property<int?>("CityId")
                        .HasColumnType("int")
                        .HasColumnName("CityID");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("PackageId")
                        .HasColumnType("int")
                        .HasColumnName("PackageID");

                    b.Property<string>("PickupPoint1")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("PickupPoint");

                    b.Property<TimeOnly?>("Time")
                        .HasColumnType("time");

                    b.HasKey("PickupPointId")
                        .HasName("PK_PickupPo_195D7E80D3E6565C");

                    b.HasIndex("CityId");

                    b.HasIndex("PackageId");

                    b.ToTable("PickupPoints");
                });

            modelBuilder.Entity("AshtavinayakAPP.Models.Seat", b =>
                {
                    b.Property<int>("SeatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SeatID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SeatId"));

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("PackageId")
                        .HasColumnType("int")
                        .HasColumnName("PackageID");

                    b.Property<string>("SeatNumber")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("TripId")
                        .HasColumnType("int")
                        .HasColumnName("TripID");

                    b.HasKey("SeatId")
                        .HasName("PK_Seats_311713D32A6E6BA9");

                    b.HasIndex("PackageId");

                    b.HasIndex("TripId");

                    b.ToTable("Seats");
                });

            modelBuilder.Entity("AshtavinayakAPP.Models.TourDestination", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("DestinationName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("TourDestination", (string)null);
                });

            modelBuilder.Entity("AshtavinayakAPP.Models.Transaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TransactionID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransactionId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("BookingId")
                        .HasColumnType("int")
                        .HasColumnName("BookingID");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime");

                    b.Property<string>("TransactionReference")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.HasKey("TransactionId")
                        .HasName("PK__Transact__55433A4BA084671B");

                    b.HasIndex("BookingId");

                    b.HasIndex("UserId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("AshtavinayakAPP.Models.Trip", b =>
                {
                    b.Property<int>("TripId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TripID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TripId"));

                    b.Property<int>("AvailableSeats")
                        .HasColumnType("int");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int")
                        .HasColumnName("CategoryID");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("PackageId")
                        .HasColumnType("int")
                        .HasColumnName("PackageID");

                    b.Property<int>("TotalSeats")
                        .HasColumnType("int");

                    b.Property<string>("TourName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("TripDate")
                        .HasColumnType("datetime");

                    b.HasKey("TripId")
                        .HasName("PK_Trip_51DC711E381FE12F");

                    b.HasIndex("CategoryId");

                    b.HasIndex("PackageId");

                    b.ToTable("Trip", (string)null);
                });

            modelBuilder.Entity("AshtavinayakAPP.Models.TripRoute", b =>
                {
                    b.Property<int>("Trid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TRID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Trid"));

                    b.Property<int?>("CityId")
                        .HasColumnType("int")
                        .HasColumnName("CityID");

                    b.Property<string>("Day")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("PackageId")
                        .HasColumnType("int")
                        .HasColumnName("PackageID");

                    b.Property<string>("PointName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Trid")
                        .HasName("PK_TripRout_82F3BB35F91260E1");

                    b.HasIndex("CityId");

                    b.HasIndex("PackageId");

                    b.ToTable("TripRoute", (string)null);
                });

            modelBuilder.Entity("AshtavinayakAPP.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("JwtToken")
                        .HasMaxLength(700)
                        .HasColumnType("nvarchar(700)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Role")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("User");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("UserId")
                        .HasName("PK_Users_1788CCACA3D5D2B8");

                    b.HasIndex(new[] { "Email" }, "UQ_Users_A9D1053426A34142")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("AshtavinayakAPP.Models.Vehicle", b =>
                {
                    b.Property<int>("VehicleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VehicleId"));

                    b.Property<string>("DriverContact")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DriverName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("TotalSeats")
                        .HasColumnType("int");

                    b.Property<int>("TripId")
                        .HasColumnType("int")
                        .HasColumnName("TripID");

                    b.Property<string>("VehicleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("VehicleNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("VehicleType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("VehicleId")
                        .HasName("PK_Vehicles_476B549245444C9B");

                    b.HasIndex("TripId");

                    b.HasIndex(new[] { "VehicleNumber" }, "UQ_Vehicles_ABAD8859CE494BD9")
                        .IsUnique();

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("AshtavinayakAPP.Models.Booking", b =>
                {
                    b.HasOne("AshtavinayakAPP.Models.Agent", "Agent")
                        .WithMany("Bookings")
                        .HasForeignKey("AgentId")
                        .HasConstraintName("FK_Bookings_Agents");

                    b.HasOne("AshtavinayakAPP.Models.PickupPoint", "PickupPoint")
                        .WithMany()
                        .HasForeignKey("PickupPointId");

                    b.HasOne("AshtavinayakAPP.Models.Trip", "Trip")
                        .WithMany("Bookings")
                        .HasForeignKey("TripId")
                        .HasConstraintName("FK_BookingsTripID_4D94879B");

                    b.HasOne("AshtavinayakAPP.Models.User", "User")
                        .WithMany("Bookings")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_Bookings_Users");

                    b.Navigation("Agent");

                    b.Navigation("PickupPoint");

                    b.Navigation("Trip");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AshtavinayakAPP.Models.BookingSeat", b =>
                {
                    b.HasOne("AshtavinayakAPP.Models.Trip", "Trip")
                        .WithMany("BookingSeats")
                        .HasForeignKey("TripId")
                        .HasConstraintName("FK_BookingSeats_Trip");

                    b.HasOne("AshtavinayakAPP.Models.User", "User")
                        .WithMany("BookingSeats")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_BookingSeats_Bookings");

                    b.Navigation("Trip");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AshtavinayakAPP.Models.Category", b =>
                {
                    b.HasOne("AshtavinayakAPP.Models.City", "City")
                        .WithMany("Categories")
                        .HasForeignKey("CityId")
                        .HasConstraintName("FK_Categories_Cities");

                    b.HasOne("AshtavinayakAPP.Models.TourDestination", "TourDestination")
                        .WithMany("Categories")
                        .HasForeignKey("TourDestinationId")
                        .HasConstraintName("FK_Categories_TourDestination");

                    b.Navigation("City");

                    b.Navigation("TourDestination");
                });

            modelBuilder.Entity("AshtavinayakAPP.Models.DropUp", b =>
                {
                    b.HasOne("AshtavinayakAPP.Models.City", "City")
                        .WithMany("DropUps")
                        .HasForeignKey("CityId")
                        .HasConstraintName("FK_DropUp_Cities");

                    b.Navigation("City");
                });

            modelBuilder.Entity("AshtavinayakAPP.Models.FamilyBooking", b =>
                {
                    b.HasOne("AshtavinayakAPP.Models.Package", "Package")
                        .WithMany("FamilyBookings")
                        .HasForeignKey("PackageId")
                        .IsRequired()
                        .HasConstraintName("FK_FamilyBooking_Packages");

                    b.HasOne("AshtavinayakAPP.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Package");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AshtavinayakAPP.Models.History", b =>
                {
                    b.HasOne("AshtavinayakAPP.Models.Booking", "Booking")
                        .WithMany("Histories")
                        .HasForeignKey("BookingId")
                        .HasConstraintName("FK_History_Bookings");

                    b.HasOne("AshtavinayakAPP.Models.Category", "Category")
                        .WithMany("Histories")
                        .HasForeignKey("CategoryId")
                        .HasConstraintName("FK_History_Categories");

                    b.HasOne("AshtavinayakAPP.Models.City", "City")
                        .WithMany("Histories")
                        .HasForeignKey("CityId")
                        .HasConstraintName("FK_History_Cities");

                    b.HasOne("AshtavinayakAPP.Models.Package", "Package")
                        .WithMany("Histories")
                        .HasForeignKey("PackageId")
                        .HasConstraintName("FK_History_Packages");

                    b.Navigation("Booking");

                    b.Navigation("Category");

                    b.Navigation("City");

                    b.Navigation("Package");
                });

            modelBuilder.Entity("AshtavinayakAPP.Models.Notification", b =>
                {
                    b.HasOne("AshtavinayakAPP.Models.Trip", "Trip")
                        .WithMany()
                        .HasForeignKey("TripId");

                    b.HasOne("AshtavinayakAPP.Models.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_Notifications_Users");

                    b.HasOne("AshtavinayakAPP.Models.Vehicle", "Vehicle")
                        .WithMany("Notifications")
                        .HasForeignKey("VehicleId")
                        .HasConstraintName("FK_Notifications_Vehicles");

                    b.Navigation("Trip");

                    b.Navigation("User");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("AshtavinayakAPP.Models.Package", b =>
                {
                    b.HasOne("AshtavinayakAPP.Models.Category", "Category")
                        .WithMany("Packages")
                        .HasForeignKey("CategoryId")
                        .HasConstraintName("FK_Packages_Categories");

                    b.HasOne("AshtavinayakAPP.Models.City", "City")
                        .WithMany("Packages")
                        .HasForeignKey("CityId")
                        .HasConstraintName("FK_PackagesCityID_6A30C649");

                    b.Navigation("Category");

                    b.Navigation("City");
                });

            modelBuilder.Entity("AshtavinayakAPP.Models.PickupPoint", b =>
                {
                    b.HasOne("AshtavinayakAPP.Models.City", "City")
                        .WithMany("PickupPoints")
                        .HasForeignKey("CityId")
                        .HasConstraintName("FK_PickupPoints_Cities");

                    b.HasOne("AshtavinayakAPP.Models.Package", "Package")
                        .WithMany("PickupPoints")
                        .HasForeignKey("PackageId")
                        .HasConstraintName("FK_PickupPoints_Packages");

                    b.Navigation("City");

                    b.Navigation("Package");
                });

            modelBuilder.Entity("AshtavinayakAPP.Models.Seat", b =>
                {
                    b.HasOne("AshtavinayakAPP.Models.Package", "Package")
                        .WithMany("Seats")
                        .HasForeignKey("PackageId")
                        .HasConstraintName("FK_SeatsPackageID_66603565");

                    b.HasOne("AshtavinayakAPP.Models.Trip", "Trip")
                        .WithMany("Seats")
                        .HasForeignKey("TripId")
                        .HasConstraintName("FK_Seats_Trip");

                    b.Navigation("Package");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("AshtavinayakAPP.Models.Transaction", b =>
                {
                    b.HasOne("AshtavinayakAPP.Models.Booking", "Booking")
                        .WithMany("Transactions")
                        .HasForeignKey("BookingId")
                        .IsRequired()
                        .HasConstraintName("FK_TransactiBooki_5441852A");

                    b.HasOne("AshtavinayakAPP.Models.User", "User")
                        .WithMany("Transactions")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Transactions_Users");

                    b.Navigation("Booking");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AshtavinayakAPP.Models.Trip", b =>
                {
                    b.HasOne("AshtavinayakAPP.Models.Category", "Category")
                        .WithMany("Trips")
                        .HasForeignKey("CategoryId")
                        .HasConstraintName("FK_Trip_Categories");

                    b.HasOne("AshtavinayakAPP.Models.Package", "Package")
                        .WithMany("Trips")
                        .HasForeignKey("PackageId")
                        .HasConstraintName("FK_TripPackageID_693CA210");

                    b.Navigation("Category");

                    b.Navigation("Package");
                });

            modelBuilder.Entity("AshtavinayakAPP.Models.TripRoute", b =>
                {
                    b.HasOne("AshtavinayakAPP.Models.City", "City")
                        .WithMany("TripRoutes")
                        .HasForeignKey("CityId")
                        .HasConstraintName("FK_TripRoute_Cities");

                    b.HasOne("AshtavinayakAPP.Models.Package", "Package")
                        .WithMany("TripRoutes")
                        .HasForeignKey("PackageId")
                        .HasConstraintName("FK_TripRoute_Packages");

                    b.Navigation("City");

                    b.Navigation("Package");
                });

            modelBuilder.Entity("AshtavinayakAPP.Models.Vehicle", b =>
                {
                    b.HasOne("AshtavinayakAPP.Models.Trip", "Trip")
                        .WithMany("Vehicles")
                        .HasForeignKey("TripId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Vehicles_Trips");

                    b.Navigation("Trip");
                });

            modelBuilder.Entity("AshtavinayakAPP.Models.Agent", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("AshtavinayakAPP.Models.Booking", b =>
                {
                    b.Navigation("Histories");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("AshtavinayakAPP.Models.Category", b =>
                {
                    b.Navigation("Histories");

                    b.Navigation("Packages");

                    b.Navigation("Trips");
                });

            modelBuilder.Entity("AshtavinayakAPP.Models.City", b =>
                {
                    b.Navigation("Categories");

                    b.Navigation("DropUps");

                    b.Navigation("Histories");

                    b.Navigation("Packages");

                    b.Navigation("PickupPoints");

                    b.Navigation("TripRoutes");
                });

            modelBuilder.Entity("AshtavinayakAPP.Models.Package", b =>
                {
                    b.Navigation("FamilyBookings");

                    b.Navigation("Histories");

                    b.Navigation("PickupPoints");

                    b.Navigation("Seats");

                    b.Navigation("TripRoutes");

                    b.Navigation("Trips");
                });

            modelBuilder.Entity("AshtavinayakAPP.Models.TourDestination", b =>
                {
                    b.Navigation("Categories");
                });

            modelBuilder.Entity("AshtavinayakAPP.Models.Trip", b =>
                {
                    b.Navigation("BookingSeats");

                    b.Navigation("Bookings");

                    b.Navigation("Seats");

                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("AshtavinayakAPP.Models.User", b =>
                {
                    b.Navigation("BookingSeats");

                    b.Navigation("Bookings");

                    b.Navigation("Notifications");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("AshtavinayakAPP.Models.Vehicle", b =>
                {
                    b.Navigation("Notifications");
                });
#pragma warning restore 612, 618
        }
    }
}
