<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="BCrypt.Net-Next" Version="4.0.3" />
		<PackageReference Include="EPPlus.Core" Version="1.5.4" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.12" />
		<PackageReference Include="Microsoft.AspNetCore.Authorization" Version="8.0.12" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.0">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.0" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.0">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.Extensions.Configuration" Version="9.0.1" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.0" />
		<PackageReference Include="Microsoft.IdentityModel.JsonWebTokens" Version="8.3.1" />
		<PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="8.0.7" />
		<PackageReference Include="Razorpay" Version="3.3.2" />
		<PackageReference Include="Select.HtmlToPdf.NetCore" Version="25.2.0" />
		<PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.3.1" />
		<PackageReference Include="System.Security.Claims" Version="4.3.0" />
	</ItemGroup>

	<ItemGroup>
		<Folder Include="wwwroot\css\NewFolder\" />
	</ItemGroup>

	<ItemGroup>
	  <Content Update="Views\Packages\Delete.cshtml">
	    <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
	    <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
	  </Content>
	</ItemGroup>

</Project>
